# Version of the docker-compose SPEC
version: "3"

services:

  api-gateway:
    image: graphql-gateway
    build: ./graphql-gateway        
    container_name: graphql-gateway
    ports:
      - 7777:7777
    networks:
      - server-net

  configuration-service:
    image: configuration-service
    build: ./configuration-service        
    container_name: configuration-service
    ports:
      - 8888:8888
    networks:
      - server-net

  service-registry:
    image: service-registry
    build: ./service-registry
    container_name: service-registry
    ports:
      - 8761:8761
    networks:
      - server-net

  vmware-service:
    image: vmware-service
    build: ./vmware-service
    container_name: vmware-service
    ports:
      - 9999:9999
    networks:
      - server-net
      
  zapi-service:
    image: ontap-service
    build: ./ontap-service
    container_name: ontap-service
    ports:
      - 5555:5555
    networks:
      - server-net

networks:
  server-net:

