server:
  port: 8888

management:
  context-path: /admin

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ppp2k1/hackathon-git-repo.git
          basedir: target/config

